### PR TITLE
restart dev-mc branch from current main

### LINKED ISSUE #94: report workflow UUID in plans with DM workflows
Make it common for all plans that run DM workflows to report the workflow UUID.  Make sure this is reported together (or close to) the bluesky run's `uid`, or else it may not be noticed.  (The DM workflow UUID might already be reported but users are not finding it.)  No instances of UUID or UID (upper or lower case) in the log files was found (except for `wf_gpuID`, which is different).

### PR DESCRIPTION
**Pull request by prjemian**
Restart the changes from the `dev-mc` branch (only local at APS, never pushed), starting from the current main branch.

- close #94

### CODE REVIEW

**Comment by prjemian** [comment]
Here are all the differences between the `dev-mc` branch and its main:

<details>

```diff
diff --git a/scripts/start_interactive_bluesky_session.sh b/scripts/start_interactive_bluesky_session.sh
index 6532ab6..d9fa5ec 100755
--- a/scripts/start_interactive_bluesky_session.sh
+++ b/scripts/start_interactive_bluesky_session.sh
@@ -36,9 +36,9 @@ fi
 # Check if a keyword was provided
 if [ -z "$1" ]; then
   # No keyword provided, prompt the user
-  echo "Please specify a keyword: ipython or jupyter"
-  read -r keyword
-  handle_keyword "$keyword"
+  # echo "Please specify a keyword: ipython or jupyter"
+  echo "Using default console: ipython"
+  handle_keyword ipython
 else
   # Keyword provided, handle it
   handle_keyword "$1"
diff --git a/src/instrument/plans/__init__.py b/src/instrument/plans/__init__.py
index 86cbbba..6e90c69 100755
--- a/src/instrument/plans/__init__.py
+++ b/src/instrument/plans/__init__.py
@@ -9,7 +9,7 @@ from .demo_hello_world import hello_world
 from .demo_sim_1d import demo_sim_1d
 
 ## beamline specific plans
-from .bdp_demo import xpcs_bdp_demo_plan
+from .bdp_demo import xpcs_bdp_demo_plan, xpcs_setup_user, xpcs_reset_index, mc_test
 from .listruns_plan import listruns
 from .mesh_plans import xpcs_mesh
 
diff --git a/src/instrument/plans/bdp_demo.py b/src/instrument/plans/bdp_demo.py
index 721711d..cc1c0db 100644
--- a/src/instrument/plans/bdp_demo.py
+++ b/src/instrument/plans/bdp_demo.py
@@ -22,6 +22,7 @@ from bluesky import plan_stubs as bps
 from bluesky import plans as bp
 from bluesky import preprocessors as bpp
 from ophyd import Signal
+import os
 
 from ..callbacks.nexus_data_file_writer import nxwriter
 from ..devices import DM_WorkflowConnector, adsim4M, dm_experiment, eiger4M, lambda2M
@@ -44,15 +45,16 @@ from ..utils.iconfig_loader import iconfig
 logger = logging.getLogger(__name__)
 logger.info(__file__)
 
-sensor = Signal(name="sensor", value=1.23456)  # TODO: developer
+# sensor = Signal(name="sensor", value=1.23456)  # TODO: developer
 xpcs_header = Signal(name="xpcs_header", value=RE.md.get("xpcs_header", "A001"))
 xpcs_index = Signal(name="xpcs_index", value=RE.md.get("xpcs_index", 0))
 
 DEFAULT_DETECTOR_NAME = "eiger4M"
 DM_WORKFLOW_NAME = iconfig.get("DM_WORKFLOW_NAME", "example-01")
-TITLE = "BDP_XPCS_demo"  # keep this short, single-word
+TITLE = "CAC Demo"  # keep this short, single-word
 DESCRIPTION = "Demonstrate XPCS data acquisition and analysis."
-DEFAULT_RUN_METADATA = {"title": TITLE, "description": DESCRIPTION}
+DEFAULT_RUN_METADATA = {"title": TITLE, "description": DESCRIPTION,
+                        "cycle": "2024-3"}
 DEFAULT_REPORTING_PERIOD = (
     10 * SECOND
 )  # time between reports about an active DM workflow
@@ -66,6 +68,7 @@ QMAP_BASE = pathlib.Path("/home/beams/8IDIUSER/Documents/Miaoqi/standard_qmaps")
 QMAPS = {
     "adsim4M": QMAP_BASE / "adsim4M_qmap_d36_s360.h5",
     "eiger4M": QMAP_BASE / "eiger4M_qmap_d36_s360.h5",
+    "eiger4M_0811_1": QMAP_BASE / 'eiger4m_qmap_after_windowadjust.h5'
 }
 
 
@@ -155,7 +158,7 @@ def xpcs_bdp_demo_plan(
     description: str = DESCRIPTION,
     header: str = xpcs_header.get(),
     analysisMachine: str = "amazonite",  # or "adamite", or "polaris"
-    qmap_file: str = str(QMAPS.get(DEFAULT_DETECTOR_NAME, "/path/to/qmap_file.hdf")),
+    qmap_file: str = 'none',
     # detector parameters ----------------------------------------
     detector_name: str = DEFAULT_DETECTOR_NAME,
     acquire_time: float = 0.01,
@@ -192,10 +195,12 @@ def xpcs_bdp_demo_plan(
     # *** Prepare. ***
     #
     analysisMachine = analysisMachine.lower()  # to be safe
-    if analysisMachine in ("adamite", "amazonite"):
-        workflow_name = "xpcs8-apsu-dev-local"
+    if analysisMachine in ("adamite", "amazonite", "califone"):
+        # workflow_name = "xpcs8-apsu-dev-local"
+        workflow_name = "xpcs8-02-gladier-boost"
     elif analysisMachine in ("polaris"):
-        workflow_name = "xpcs8-apsu-dev-polaris"
+        # workflow_name = "xpcs8-apsu-dev-polaris"
+        workflow_name = "xpcs8-02-gladier-boost"
     else:
         raise ValueError(
             f"Received {analysisMachine=!r}."
@@ -230,11 +235,12 @@ def xpcs_bdp_demo_plan(
         det.hdf1, data_path, file_name_base, num_capture=num_images
     )
 
-    qmap_path = QMAPS[det.name]
-    if str(qmap_file).strip() == "":
-        qmap_file = str(qmap_path)
-    if not pathlib.Path(qmap_file).exists():
-        raise FileNotFoundError(f"QMAP file: {qmap_file!r}")
+    if os.path.isfile(qmap_file):
+        qmap_path = pathlib.Path(qmap_file)
+        logger.info(f'using qmap:{qmap_file=}')
+    else:
+        raise ValueError('Qmap does not exist')
+
     # upload QMAP to @voyager
     daqInfo_qmap_upload = dm_api_daq().upload(
         experimentName=experiment_name,
@@ -271,22 +277,22 @@ def xpcs_bdp_demo_plan(
         # values from pete7.hdf
         # TODO: set from actual instrument values
         absolute_cross_section_scale=1,
-        bcx=0,
-        bcy=0,
+        bcx=1044,
+        bcy=1416,
         ccdx=1,
         ccdx0=1,
         ccdy=1,
         ccdy0=1,
-        det_dist=4,
+        det_dist=12.5,
         I0=1,
         I1=1,
-        incident_beam_size_nm_xy=1,
+        incident_beam_size_nm_xy=10000,
         incident_energy_spread=1,
-        pix_dim_x=1,
-        pix_dim_y=1,
-        t0=0.005,
-        t1=0.001,
-        X_energy=12.0,
+        pix_dim_x=75e-6,
+        pix_dim_y=75e-6,
+        t0=acquire_time,
+        t1=acquire_period,
+        X_energy=13.321,
         xdim=1,
         ydim=1,
     )
@@ -372,7 +378,7 @@ def xpcs_bdp_demo_plan(
         timeout=dm_reporting_time_limit,
         # all kwargs after this line are DM argsDict content
         filePath=pathlib.Path(det.hdf1.full_file_name.get()).name,
-        experiment=dm_experiment.get(),
+        experimentName=dm_experiment.get(),
         qmap=qmap_path.name,
         # from the plan's API
         smooth=wf_smooth,
@@ -395,17 +401,42 @@ def xpcs_bdp_demo_plan(
     logger.info("Finished: xpcs_bdp_demo_plan()")
 
 
-def prj_test(detector_name: str = DEFAULT_DETECTOR_NAME, index: int = 0):
+def prj_test(detector_name: str = DEFAULT_DETECTOR_NAME, index: int = 0,
+             num_trys: int = 10):
     """Developer shortcut plan."""
-    yield from xpcs_setup_user("20240131-jemian", index=index)
+    yield from xpcs_setup_user("dm-test-bs-MC", index=index)
     qmap_path = QMAPS.get(detector_name)
     if qmap_path is None:
         raise FileNotFoundError(f"QMAP file {qmap_path} not found.")
-    yield from xpcs_bdp_demo_plan(
-        header="A002",
-        detector_name=detector_name,
-        qmap_file=str(qmap_path),
-        dm_wait=False,
-        dm_concise=True,
-        analysisMachine="adamite",
-    )
+    
+    for n in range(num_trys):
+        yield from xpcs_bdp_demo_plan(
+            header="A001",
+            detector_name=detector_name,
+            qmap_file=str(qmap_path),
+            dm_wait=False,
+            dm_concise=True,
+            analysisMachine="adamite",
+        )
+
+
+def mc_test(detector_name: str = DEFAULT_DETECTOR_NAME, index: int = 0,
+             num_trys: int = 10):
+    """Developer shortcut plan."""
+    qmap_path = QMAPS.get(detector_name)
+    if qmap_path is None:
+        raise FileNotFoundError(f"QMAP file {qmap_path} not found.")
+    
+    for n in range(10):
+        yield from xpcs_bdp_demo_plan(
+            header="G10",
+            detector_name=detector_name,
+            qmap_file=str(qmap_path),
+            dm_wait=False,
+            dm_concise=True,
+            analysisMachine="adamite",
+            wf_gpuID=0,
+            acquire_time=0.01,
+            acquire_period=0.01,
+            num_images=1_000,
+        )
```

</details>

**Comment by prjemian** [comment]
@AZjk - Just sent you an invite to join the team here.  Once you accept, can add you as reviewer.

**Comment by AZjk** [comment]
It looks good to me. Please feel free to merge

**Comment by prjemian** [comment]
Should we try it at the beamline first, then merge if OK?

**Comment by prjemian** [comment]
@AZjk - Now, you are a reviewer!

**Review by MDecarabas — APPROVED** [review]

**Pull request merged**
