### PR TITLE
Transfocators in 8idd and e

### LINKED ISSUE #61: Transfocator in 8-ID-D & 8-ID-E
### move

image

### lenses

image

### PR DESCRIPTION
**Pull request by prjemian**
- close #61

### CODE REVIEW

**Review by MDecarabas — COMMENTED** [review]
Do you think we should initialize both devices in the same file since they use the same class? On one hand less code, on another we encounter the initialization problem Victoria was discussing yesterday. Thoughts?

**Comment by prjemian** [comment]
> Do you think we should initialize both devices in the same file since they use the same class? On one hand less code, on another we encounter the initialization problem Victoria was discussing yesterday. Thoughts?

Just like yesterday's discussion.  As @sureshnaps stated:

> 8IDI should not load all the 8IDE devices

If they are in one file, both will be connected.

**Comment by prjemian** [comment]
I thought about a reuseable class which could be used by both.  But that would make the code larger and look much more complicated.  Instead, chose to write using the same class name but different motor numbers internally.  

These classes are singletons.  Could rename them with a preceding `_` to hint they are local definitions of the class and not intended for re-use.

**Comment by MDecarabas** [comment]
> I thought about a reuseable class which could be used by both. But that would make the code larger and look much more complicated. Instead, chose to write using the same class name but different motor numbers internally.
> 
> These classes are singletons. Could rename them with a preceding `_` to hint they are local definitions of the class and not intended for re-use.

No need, let's go ahead like this for now and we can chat at a later time about a more elegant permanent solution

**Review by MDecarabas — APPROVED** [review]

**Pull request merged**
