### PR TITLE
flag1ad & flag2ad PROC1 plugins

### LINKED ISSUE #50: flag2ad : Could not list component
```py
In [4]: listdevice(flag2ad)
Could not list component: flag2ad_proc1.high_clip
Could not list component: flag2ad_proc1.low_clip

In [5]: flag2ad.proc1.high_clip
Ignoring component with duplicate name: 'flag2ad_proc1_high_clip'
/home/beams/8IDIUSER/.conda/envs/bstest/lib/python3.10/site-packages/ophydregistry/registry.py:558: UserWarning: Ignoring component with duplicate name: 'flag2ad_proc1_high_clip'
  warnings.warn(msg)
Ignoring component with duplicate name: 'flag2ad_proc1_high_clip'
KeyError: 'high_clip'

During handling of the above exception, another exception occurred:
TimeoutError: 8idaSoft:flag2:Proc1:HighClip_RBV could not connect within 5.0-second timeout.

```

### PR DESCRIPTION
**Pull request by prjemian**
- close #50 remove PROC1 plugins from flag area detector support

### CODE REVIEW

**Review by MDecarabas — APPROVED** [review]
Looks good, can you please add a comment as to what the added setting does for clarity please

**Comment by prjemian** [comment]
Other plugins might also be unused.  These flag detectors are not a high priority now.  Good enough to have no errors.

**Comment by prjemian** [comment]
But this error, too:

```py
Ignoring component with duplicate name: 'flag2ad_stats1_sigma_y'
RuntimeError: Invalid array size (0, 0, 0)

```

Don't need stats1 or roi1 plugins.

**Comment by prjemian** [comment]
Still:

```py
In [1]: listdevice(flag1ad)
Subscription value callback exception (EpicsSignal(read_pv='8idaSoft:flag1:image1:ArrayData', name='flag1ad_image_array_data', parent='flag1ad_image', value=array([], dtype=uint8), timestamp=631152000.0, auto_monitor=True, string=False, write_pv='8idaSoft:flag1:image1:ArrayData', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bstest/lib/python3.10/site-packages/ophyd/device.py", line 325, in __get__
    return instance._signals[self.attr]
KeyError: 'shaped_image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bstest/lib/python3.10/site-packages/ophyd/ophydobj.py", line 492, in inner
    cb(*args, **kwargs)
  File "/home/beams/8IDIUSER/.conda/envs/bstest/lib/python3.10/site-packages/ophyd/signal.py", line 696, in _derived_value_callback
    value = self.inverse(value)
  File "/home/beams/8IDIUSER/.conda/envs/bstest/lib/python3.10/site-packages/ophyd/areadetector/base.py", line 123, in inverse
    raise RuntimeError(f"Invalid array size {self.derived_shape}")
RuntimeError: Invalid array size (0, 0, 0)
Subscription value callback exception (EpicsSignal(read_pv='8idaSoft:flag1:image1:ArrayData', name='flag1ad_image_array_data', parent='flag1ad_image', value=array([], dtype=uint8), timestamp=631152000.0, auto_monitor=True, string=False, write_pv='8idaSoft:flag1:image1:ArrayData', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bstest/lib/python3.10/site-packages/ophyd/ophydobj.py", line 492, in inner
    cb(*args, **kwargs)
  File "/home/beams/8IDIUSER/.conda/envs/bstest/lib/python3.10/site-packages/ophyd/signal.py", line 696, in _derived_value_callback
    value = self.inverse(value)
  File "/home/beams/8IDIUSER/.conda/envs/bstest/lib/python3.10/site-packages/ophyd/areadetector/base.py", line 123, in inverse
    raise RuntimeError(f"Invalid array size {self.derived_shape}")
RuntimeError: Invalid array size (0, 0, 0)
RuntimeError: Invalid array size (0, 0, 0)
```

Might be unprimed, might be something else.  Make new issue for this.

**Pull request merged**
